### ISSUE TITLE
#featurerequest add signature per account/global

### ISSUE THREAD

**Issue by TheRojam** [mwnx/mutterer#12]
is there any chance to add an signature per default/global or per account?

**Comment by mwnx** [comment]
Hi,

This is already supported! As it stands, there are three ways of
defining signatures with mutterer:

1. Recommended: Use mutterer's 'signature' variable (used by
   "presets/defaults"). Here's my config for two of my accounts ("m"
   and "mwnx"):

    [accounts m mwnx]
    signature = "%name\nGPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726"

   or, if you've already defined an "all" group, you could do this:

    [accounts %all]
    signature = "%name\nGPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726"

2. Use a signature file. Just put your signature text in a file with
   path ~/.mutterer/%id.sig, where %id is the mutterer account's
   name, (e.g. m or mwnx). Mutterer will detect the file
   automatically if you haven't specified a 'signature' variable
   already.

3. You can define mutt config variables directly yourself, including
   mutt's 'signature' variable, using the 'mutt.' prefix, but this
   is a little more involved in the case of the 'signature'
   variable, so I don't recommend it. Here's how it's defined in
   presets/defaults, and how the two previous methods work under the
   hood:

    mutt.signature ?= "$(\
        if [[ -z "%{signature:+-}" ]]; then echo "~/.mutterer/%{id}.sig";\
        else echo "\"echo \\\"%signature\\\" |\"";\
        fi\
    )"

On Thu, Apr 06, 2017 at 03:52:09AM -0700, Anton wrote:
> is there any chance to add an signature per default/global or per account?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mwnx/mutterer/issues/12

-- 
mwnx
GPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726

**Comment by TheRojam** [comment]
i meant an mail signature with best regards and so on.

**Comment by mwnx** [comment]
Well, this _is_ for email signatures. For instance:

    signature = "Bob Smith\nSoftware architect"

will be formated as:

    -- 
    Bob Smith
    Software Architect

at the end of each email you write. You might simply have been
confused by the fact I include a GPG fingerprint in my signature.

Of course, this wouldn't work too well for a closing phrase like
"Best regards,", but that's not really what automatic signatures are
meant for (or at least not in mutt).

If you really want to use the 'signature' variable for closing
phrases, you can just unset mutt's 'sig_dashes' variable, either in
your mutterer config, or in .mutt/muttrc directly:

- In .muttererrc:

    [accounts <...>]
    <...>
    mutt.sig_dashes = no

- Or, in .mutt/muttrc:

    sig_dashes = no

You can then define your 'signature' variable something like:

    signature = "Best regards,\n\n-- \nBob Smith\nSoftware Architect"

Relevant entries from mutt's manual:

    3.261. sig_dashes

    Type: boolean
    Default: yes

    If set, a line containing “-- ” (note the trailing space) will
    be inserted before your $signature. It is strongly recommended
    that you not unset this variable unless your signature contains
    just your name. The reason for this is because many software
    packages use “-- \n” to detect your signature. For example, Mutt
    has the ability to highlight the signature in a different color
    in the built-in pager.

    3.262. sig_on_top

    Type: boolean
    Default: no

    If set, the signature will be included before any quoted or
    forwarded text. It is strongly recommended that you do not set
    this variable unless you really know what you are doing, and are
    prepared to take some heat from netiquette guardians.

    3.263. signature

    Type: path Default: “~/.signature”

    Specifies the filename of your signature, which is appended to
    all outgoing messages. If the filename ends with a pipe (“|”),
    it is assumed that filename is a shell command and input should
    be read from its standard output.

On Mon, Apr 10, 2017 at 03:34:55AM -0700, Anton wrote:
> i meant an mail signature with best regards and so on.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/mwnx/mutterer/issues/12#issuecomment-292912550

-- 
mwnx
GPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726

**Comment by TheRojam** [comment]
i understood now ... after reading it again 🙈 😅
