### ISSUE TITLE
pythonfile for the purpose of secure passwords

### ISSUE THREAD

**Issue by 97-109-107** [mwnx/mutterer#8]
I would like to utilize an external script/tool to supply the imap passwords to offlineimap/msmtp. For reference, I'm using this as an outline http://unix.stackexchange.com/a/48355

However, if I try to configure it in the ``~/.muttererrc`` file:
````
[general]
pythonfile      = ~/.offlineimap/passcmd.py
imap.accounts   = <account name>
```` 

the statement isn't reflected in the outputted config files.

I searched the source and couln't find any instance of the word ``pythonfile``, does that mean that while parsing, mutterer simply ignores unknown properties?

**Comment by 97-109-107** [comment]
I figured out how to add a property being translated, I simply went ahead with a change like this:
````
diff --git a/presets/defaults b/presets/defaults
index a13008e..26c4d6f 100644
--- a/presets/defaults
+++ b/presets/defaults
@@ -132,7 +132,6 @@ imap.Repository remote_%{id}.remoteport ?~= $([[ ! "%{imap_host}" =~ : ]] || ech
 imap.Repository remote_%{id}.ssl        ?~= %{imap_ssl:-}
 imap.Repository remote_%{id}.remotepass  ?= %{password}
 imap.Repository remote_%{id}.folderfilter ?~= %{imap_filter:-}
-imap.Repository remote_%{id}.pythonfile ?~= %{pythonfile:-}
 # imap.Repository.remote_${id}.sslcacertfile = ...
 
 [accounts %{smtp_defaults:-}]
````
I  can make pull request for this if you want to. However, I feel like this is not solving the issue I have all the way. Soon, I will try to add the same decryption mechanisms for msmtp, but that requires a different approach according to this source: https://wiki.archlinux.org/index.php/OfflineIMAP#Using_GPG

I'm writing this here instead of going ahead because I would like to know if you know of a smarter solution to this than what I'm trying to brute-force here.

**Comment by mwnx** [comment]
On Thu, Aug 13, 2015 at 07:23:51AM -0700, 97-109-107 wrote:
> I would like to utilize an external script/tool to supply the imap passwords to offlineimap/msmtp. For reference, I'm using this as an outline http://unix.stackexchange.com/a/48355
> 
> However, I if try to configure it in the ``~/.muttererrc`` file:
> ````
> [general]
> pythonfile      = ~/.offlineimap/passcmd.py
> imap.accounts   = <account name>
> ```` 
> 
> the statement isn't reflected in the outputted config files.
> 
> I searched the source and couln't find any instance of the word ``pythonfile``, does that mean that while parsing, mutterer simply ignores unknown properties? 

Yes, Mutterer is basically just a scripting tool, a wrapper around bash. If
a variable is not referenced anywhere else, it won't have any effect.

On Thu, Aug 13, 2015 at 07:36:51AM -0700, 97-109-107 wrote:
> I figured out how to add a property being translated, I simply went ahead with a change like this:
> ````
> diff --git a/presets/defaults b/presets/defaults
> index a13008e..26c4d6f 100644
> --- a/presets/defaults
> +++ b/presets/defaults
> @@ -132,7 +132,6 @@ imap.Repository remote_%{id}.remoteport ?~= $([[ ! "%{imap_host}" =~ : ]] || ech
>  imap.Repository remote_%{id}.ssl        ?~= %{imap_ssl:-}
>  imap.Repository remote_%{id}.remotepass  ?= %{password}
>  imap.Repository remote_%{id}.folderfilter ?~= %{imap_filter:-}
> -imap.Repository remote_%{id}.pythonfile ?~= %{pythonfile:-}
>  # imap.Repository.remote_${id}.sslcacertfile = ...
>  
>  [accounts %{smtp_defaults:-}]
> ````
> I  can make pull request for this if you want to. However, I feel like this is not solving the issue I have all the way. Soon, I will try to add the same decryption mechanisms for msmtp, but that requires a different approach according to this source: https://wiki.archlinux.org/index.php/OfflineIMAP#Using_GPG
> 
> I'm writing this here instead of going ahead because I would like to know if you know of a smarter solution to this than what I'm trying to brute-force here.

I've never looked into solutions beside plaintext passwords, but from what I
can see in msmtp's man page, it should be possible for it to use the system
keyring:

    [...] If that  fails, it  will  try to get it from a system specific
    keyring (if avail‐ able). If that fails but a  controlling  terminal  is
    available, msmtp will prompt you for it. Currently supported keyrings
    are the Gnome Keyring and the Mac OS X Keychain.  The script
    msmtp-gnome-tool.py can be used to manage Gnome  Keyring  passwords  for
    msmtp. To manage Mac OS X Keychain passwords, use the Keychain Access
    GUI application.  The  account name  is  same as the msmtp user
    argument. The keychain item name is smtp://<hostname> where  <hostname>
    matches  the  msmtp  host argument.

So it might be possible to use the same keyring entry for both msmtp and
offlineimap, thus saving the user from some boilerplate, which after all, is
Mutterer's purpose.

If this works out, it should be possible to update the "defaults" preset
somewhat like this (completely untested):

-imap.Repository remote_%{id}.remotepass  ?= %{password}
+imap.Repository remote_%{id}.remotepass  ?~= %{password:-}

+imap.Repository remote_%{id}.remotepasseval = "$(\
+    [[ -n "%{password:-}" ]] ||\
+    printn "get_password(\"mutterer-%id\")")"

+[Same thing for for msmtp]


                                   * * *

Another solution is to use pgp encrypted password file, which might be more
in the spirit of what Mutterer users are looking for.

Msmtp's man page gives the following example for gpg support:

    passwordeval gpg -d ~/.msmtp.password.gpg

which could become, in Mutterer:

    smtp.passwordeval ?~= "$(\
        [[ -n "%{password:-}" ]] ||\
        printn "gpg -d \"~/mutterer/passwords/%id.gpg\"")"

Offlineimap doesn't give any example for gpg but it should be very simple by
just adapting the remotepasseval example:

    remotepasseval = get_password("imap.acc1.net")

to something like (I haven't done much python so please excuse me):

    remotepasseval = os("gpg -d ~/mutterer/passwords/%id.gpg")

                                   * * *

If you tell me which method you prefer I can try and implement it first and
add it to the experimental branch where you can test it. I'll probably add
the alternative method later, and make the prefered method selectable using
a switch.

Of course, if you want to hack a solution up yourself, be my guest. The
patch (a.k.a. PR) you send should deal with both offlineimap and msmtp, and
require only one password file or keyring entry for both, in the spirit of
limiting duplication of code and effort for the end user.


Thanks for you interest in Mutterer!

**Comment by mwnx** [comment]
Well, github made a huge mess of formatting my response, so here's a pastebin link in case you're not reading this from your mail client: http://pastebin.com/raw.php?i=tshTVpJa

**Comment by 97-109-107** [comment]
Thank you for your prompt and thourough reply! I got around the formatting, thank you. 

I'm personally more interested in the latter approach.

As a side note, as far as I read, the actual command for obtaining a password would be ``gpg -q --for-your-eyes-only --no-tty -d ~/.keys/...`` as the command you quoted seems to provide some sort of headers as well.
 
I will try to contribute, but so far there are a lot of moving pieces in my mail setup, but I'm actively interested in moving to the mutterer stack.

**Comment by 97-109-107** [comment]
Reading a bit deeper into what you wrote and imapsync, I believe that this step:

> Offlineimap doesn't give any example for gpg but it should be very simple by
> just adapting the remotepasseval example:
> 
>     remotepasseval = get_password("imap.acc1.net")
> 
> to something like (I haven't done much python so please excuse me):
> 
>     remotepasseval = os("gpg -d ~/mutterer/passwords/%id.gpg")

Won't be that simple, as it seems to that one is supposed to source an externally located script first, then call the actual function it defines where needed. I'm not familiar with mutterer's structure enough, but it looks like the script for 'picking up' password files would need to be part of .mutterer and be called in with the name of the account as the argument.

For example ``~/.mutterer/lib/decrypt_gpg_wrapper.py``:

````
def decrypt_gpg(acct):
  path = "~/.mutterer/passwords/" + acct + ".gpg"
  args = ["gpg", "-q", "--for-your-eyes-only","--no-tty", path]
  try:
    return subprocess.check_output(args).strip()
  except subprocess.CalledProcessError:
    return ""
````

And would be called like this in mutterer:

````
imap.remotepasseval = decrypt_gpg("%id")
````

The code is approximate and I haven't included the necessary sourcing
````
    pythonfile = ~/.mutterer/lib/decrypt_gpg_wrapper.py
````
which need to eventually end up in ``~/.offlineimaprc``

**Comment by mwnx** [comment]
I was under the impression that the "remotepasseval" variable worked in the
same way as the "folderfilter" variable, where the right hand side can be
any valid python expression. For instance, I have this line in
presets/detect:

    imap_filter       ?= "lambda f: f not in '[Gmail]/All Mail'"

and this one in presets/defaults:

    imap.Repository remote_%{id}.folderfilter ?~= %{imap_filter:-}

Which in the end expands to:

    imap.Repository remote_%{id}.folderfilter ?~= "lambda f: f not in '[Gmail]/All Mail'"

Only difference is that "folderfilter" expects the rhs to be a function
whereas "remotepasseval" expects the rhs to be a simple value.

Of course, I am not fundamentally opposed to including an external file with
"pythonfile" but I'm guessing a "pythonfile = ..." statement can only happen
once per account in the offlineimaprc. As a result, using the "pythonfile"
variable within mutterer would have the negative side effect of preventing
the mutterer user from defining his own "pythonfile" as he sees fit without
breaking mutterer's built-in password file feature.

I'm not sure why you don't want to just use os.system("<gpg command here>")
in this case but from what I can figure out about python, you could
transform your code into something like:

    (lambda acct:\
       path = "~/.mutterer/passwords/" + acct + ".gpg"\
       args = ["gpg", "-q", "--for-your-eyes-only","--no-tty", path]\
       try:\
         return subprocess.check_output(args).strip()\
       except subprocess.CalledProcessError:\
         return "")("%id")

Not sure if that is the simplest way of doing things or if the indentation
is correct in this context, but you get the gist.

Although now that I think about it, that wouldn't work due to the fact that
mutterer doesn't insert newline characters after newline escaping with
backslashes, something python wouldn't be too happy about. So I'll either
have to modify mutterer's parser or you can do something ugly like this:

    ... = "$(printf "%s\n%s\n%s\n%s\n"\
       "(lambda acct:"\
       "   path = \"~/.mutterer/passwords/\" + acct + \".gpg\"\
       "   args = [\"gpg\", \"-q\", \"--for-your-eyes-only\",\"--no-tty\", path]"\
       "   try:"\
       "     return subprocess.check_output(args).strip()\"\
       "   except subprocess.CalledProcessError:"\
       "     return \"\")(\"%id\")")

Yikes :D

**Comment by 97-109-107** [comment]
I'm goint to try to test this and report asap.

*Btw, there's something wrong with your encoding(?) or something, line breaks for example cannot be copied, whitespace dissappears.*

**Comment by mwnx** [comment]
> *Btw, there's something wrong with your encoding(?) or something, line breaks for example cannot be copied, whitespace dissappears.*

If you mean the encoding of my message, I don't know. I sent it as plaintext
email. Maybe github did something to it. I think if you receive it by email,
it should be fine. I can provide a pastebin for next time I guess.

Don't hesitate to contact me if you have any trouble or questions.

**Comment by mwnx** [comment]
Sorry, I didn't see your edit since github doesn't send edited messages by
email...

So, I thought about this a bit more and looked into python's doc. As it
turns out, os.system() doesn't do what I thought it did. The function
I wanted is subprocess.checkoutput([...]).

Anyway, it seems a reasonable thing to do would be to have the
lib/m_printer:print_imap function print the pythonfile somewhere (like
~/.offlineimap/pythonfile.py), and add this to presets/defaults:

    [general]
    imap.pythonfile = ~/.offlineimap/pythonfile.py

Have the contents of ~/.offlineimap/pythonfile.py (printed by the same
print_imap function) be:

    import subprocess
    import ~/.offlineimap/userpythonfile.py (or whatever the proper
                                             formulation is)

userpythonfile.py would just be empty by default, but the end user could add
whatever extra stuff he may want there.

And we could finally have this line in presets/defaults:

    imap.Repository remote_%{id}.remotepasseval ?= \
        "subprocess.checkoutput(\"gpg...\", \"%id\")"

Alternatively (this may be cleaner, I'm not sure, but mutterer is pretty
dirty already anyway :D), put your decrypt_gpg function in pythonfile.py.

Given what needs to be done, it seems more reasonable that I do it myself.
Still if you want to do it, I'm not stopping you. Tell me either way. If you
let me do it I'll definitely give you a big shout out in the commit message
:)

**Comment by 97-109-107** [comment]
I have much of you described working already. Thank you for your offer :).

I already have the decrypt python function sourced, the decryption call is used to provide password for both offlineimap and msmtp. I need to clean it up a bit and document. Hoping to do a pull request soon
